import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faMagnifyingGlass,
  faCartShopping,
  faBars,
  faArrowRightLong,
  faChevronRight,
  faHouse,
  faShop,
  faXmark,
  faTruckFast,
  faCreditCard,
  faUmbrella,
  faHeadphonesSimple,
  faHeart as faSolidHeart,
  faStar,
  faChartSimple,
  faExpand,
  faChevronDown,
  faChevronUp,
  faPhone,
  faPlus,
  faMinus,
} from "@fortawesome/free-solid-svg-icons";
import {
  faUser,
  faHeart,
  faEnvelope,
  faClock,
} from "@fortawesome/free-regular-svg-icons";
import {
  faFacebookF,
  faPinterest,
  faXTwitter,
  faTiktok,
  faVimeo,
} from "@fortawesome/free-brands-svg-icons";
export const globalIcons = () => {
  return library.add([
    faMagnifyingGlass,
    faUser,
    faHeart,
    faCartShopping,
    faBars,
    faArrowRightLong,
    faChevronRight,
    faFacebookF,
    faPinterest,
    faXTwitter,
    faTiktok,
    faHouse,
    faShop,
    faXmark,
    faTruckFast,
    faCreditCard,
    faUmbrella,
    faHeadphonesSimple,
    faSolidHeart,
    faStar,
    faChartSimple,
    faExpand,
    faChevronDown,
    faChevronUp,
    faPhone,
    faEnvelope,
    faClock,
    faVimeo,
    faPlus,
    faMinus,
  ]);
};
